# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Govind Bhardwaj
email: govindbhardwaj@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
         Full-Stack developer, DevOps Engineer, Tech-enthusiast and
         open source contributor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kumargovind88
github_username:  govindbhardwaj

# Build settings
markdown: kramdown
#theme: minima
theme: jekyll-theme-hydejack
# plugins:
#   - jekyll-feed
#   - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# A shorter description for the sidebar.
tagline:               >
  Full-Stack developer, DevOps Engineer, Tech-enthusiast and
  open source contributor.

# A list of keywords for your blog
keywords:              []

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/icons/icon.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name:                Govind Bhardwaj
  email:               govindbhardwaj@outlook.com
  # Used by `jekyll-seo-tag`:
  # twitter:             <username>

# plugins:
# - octopress-debugger

# Add links to the sidebar.
menu:
  - title:             Bio
    url:               /bio/
  - title:             Education and Certifications
    url:               /education/
  - title:             Skills
    url:               /skills/
  - title:             Work Experience
    url:               /experience/
  - title:             Interest
    url:               /interests/


# Collections
# ========================================================================================

collections:
  featured_categories:
    permalink:         /:name/
    output:            true

  featured_tags:
    permalink:         /tag-:name/
    output:            true

  projects:
    permalink:         /projects/:path/
    output:            true


# Add links to the footer.
# Typically you'll want to link to your cookie- or privacy policy (if appliable), etc..
# legal:
#   - title:             Impress
#     url:               /impress/
#   - title:             Cookies Policy
#     url:               /cookies-policy/

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2018. All rights reserved.

# Format of the permalinks
permalink:             /:categories/:year-:month-:day-:title/

# Pagination configuration (used by the `blog` layout)
paginate:              5
paginate_path:         /blog/page-:num/


# Customizaton
# ========================================================================================

# Sidebar image and theme color of the site.
accent_image:          /assets/img/sidebar-bg.jpg
accent_color:          rgb(79,177,186)

# This is used for the `theme-color` meta tag,
# which changes the background color of the browser UI in certain browsers.
# Defaults to `accent_color`.
theme_color:           rgb(25,55,71)

# The string encoding which fonts to fetch from Google Fonts.
# See: <https://hydejack.com/docs/configuration/>
google_fonts:          Roboto+Slab:400|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font:                  Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif

defaults:
  - scope:
      path:            hyde
    values:
      accent_color:    rgb(38,139,210)
      accent_image:
        background:    rgb(32,32,32)
        overlay:       false

  # `jekyll-seo-tag` will mark collection outputs as `BlogPosting`,
  # but we want them to be `WebPage`s:
  - scope:
      type:            projects
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_categories
    values:
      seo:
        type:          WebPage
  - scope:
      type:            featured_tags
    values:
      seo:
        type:          WebPage
